services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    ports:
      - "6379:6379"
    volumes:
      - ./local/docker-volumes/redis:/data

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: helloworld-commerce
      MYSQL_ROOT_PASSWORD: mysql
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./local/docker-volumes/mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka-kraft
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: >
        PLAINTEXT://kafka-kraft:29092,
        CONTROLLER://kafka-kraft:29093,
        PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka-kraft:29092,
        PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    container_name: "kafdrop"
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka-kraft:29092
      - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
      - kafka

volumes:
  mysql_data:
  redis_data:
